name: jar_video_player
description: A modern reels-ready customizable network video player for Flutter with lifecycle and visibility handling.
version: 0.1.1

homepage: https://github.com/sagarbisht-jarvsi/jar_video_player
repository: https://github.com/sagarbisht-jarvsi/jar_video_player
issue_tracker: https://github.com/sagarbisht-jarvsi/jar_video_player/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.8.2
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

topics:
  - video
  - player
  - reels
  - media
